pipeline{
   agent any
   stages{

     stage("Initializing terraform"){
       steps{
          sh '''
          terraform -chdir=/var/lib/jenkins/workspace/deploymentPipeline/Terraform/cluster apply
          terraform init
          '''
       }
     }
     stage("Terraform Plan"){
       steps{
          sh 'terraform plan'
       }
     }
     stage("Terraform apply"){
       steps{
         sh 'terraform apply'
       }
     }
   }
}